#ifndef HARDWARE_DEFINITIONS_H
#define HARDWARE_DEFINITIONS_H

#define STATUS_LED_PIN 2
#define SWITCH_1_PIN 5
#define BOOT_PIN 0

#define STATUS_LED_PIN_BITMASK (1ULL << STATUS_LED_PIN)
#define SWITCH_1_PIN_BITMASK (1ULL << SWITCH_1_PIN)
#define BOOT_PIN_BITMASK (1ULL << BOOT_PIN)

#endif